const authorsData = [
  ['John Doe', 'Harvest University', '1980-01-01', 35, 'Male', 1],
  ['Jane Smith', 'Stanford University', '1985-03-15', 45, 'Female', 2],
  [
    'Richard Johnson',
    'University of California, Berkeley',
    '1977-04-22',
    27,
    'Male',
    3,
  ],
  ['Emily Brown', 'University of Cambridge', '1982-06-06', 30, 'Female', 4],
  ['David Lee', 'Princeton University', '1979-07-07', 40, 'Male', 5],
  [
    'Sarah Johnson',
    'Massachusetts Institute of Technology',
    '1984-08-08',
    35,
    'Female',
    6,
  ],
  ['Michael Anderson', 'University of Oxford', '1981-09-09', 38, 'Male', 7],
  ['Rachel Davis', 'University of Chicago', '1983-10-10', 45, 'Female', 8],
  [
    'James Thompson',
    'California Institute of Technology',
    '1980-11-11',
    30,
    'Male',
    9,
  ],
  ['Jessica Wilson', 'Yale University', '1984-12-12', 27, 'Female', 10],
  ['Robert Johnson', 'University of Michigan', '1979-01-01', 35, 'Male', 11],
  [
    'Elizabeth Brown',
    'University of Texas at Austin',
    '1982-02-02',
    45,
    'Female',
    12,
  ],
  [
    'Thomas Davis',
    'University of Wisconsin-Madison',
    '1981-03-03',
    38,
    'Male',
    13,
  ],
  ['Mary Wilson', 'Columbia University', '1983-04-04', 35, 'Female', 14],
  ['Christopher Anderson', 'Stanford University', '1980-05-05', 30, 'Male', 15],
  [
    'Jennifer Davis',
    'University of Pennsylvania',
    '1984-06-06',
    27,
    'Female',
    16,
  ],
  ['Brian Thompson', 'University of Minnesota', '1981-07-07', 35, 'Male', 17],
  [
    'Karen Brown',
    'University of Colorado Boulder',
    '1982-08-08',
    45,
    'Female',
    18,
  ],
  ['Paul Davis', 'Stanford University', '1981-07-07', 35, 'Male', 19],
  ['Emily Wilson', 'Yale University', '1982-08-08', 45, 'Female', 20],
  ['John Anderson', 'University of Virginia', '1980-05-05', 30, 'Male', 21],
  ['Laura Davis', 'Northwestern University', '1984-06-06', 27, 'Female', 22],
  ['Michael Thompson', 'Yale University', '1981-07-07', 35, 'Male', 23],
  ['Samantha Brown', 'University of Georgia', '1982-08-08', 45, 'Female', 24],
  ['James Anderson', 'University of Arizona', '1980-05-05', 30, 'Male', 15],
  ['Emily Davis', 'University of Oregon', '1984-06-06', 27, 'Female', 16],
  ['David Thompson', 'University of Utah', '1981-07-07', 35, 'Male', 7],
  ['Sarah Brown', 'University of Pittsburgh', '1982-08-08', 45, 'Female', 12],
];

const mentorsData = [
  ['Dr. John Smith'],
  ['Dr. Richard Brown'],
  ['Dr. Emily Johnson'],
  ['Dr. David Lee'],
  ['Dr. Sarah Anderson'],
  ['Dr. Michael Davis'],
  ['Dr. Rachel Wilson'],
  ['Dr. James Thompson'],
  ['Dr. Jessica Brown'],
  ['Dr. Robert Johnson'],
  ['Dr. Elizabeth Davis'],
  ['Dr. Thomas Anderson'],
  ['Dr. Mary Wilson'],
  ['Dr. Christopher Davis'],
  ['Dr. Jennifer Anderson'],
  ['Dr. Brian Thompson'],
  ['Dr. Karen Brown'],
  ['Dr. Paul Davis'],
  ['Dr. Emily Anderson'],
  ['Dr. Laura Wilson'],
  ['Dr. Michael Anderson'],
  ['Dr. Samantha Brown'],
  ['Dr. Emily Anderson'],
  ['Dr. William Thompson'],
];

const papersData = [
  [
    'A Study of Quantum Mechanics',
    'International Conference on Quantum Mechanics',
    '2011-06-01',
    1,
  ],
  [
    'The Effects of Gravity on Time',
    'International Conference on General Relativity',
    '2011-07-15',
    2,
  ],
  [
    'The Structure of the Universe',
    'International Conference on Astrophysics',
    '2011-08-20',
    3,
  ],
  [
    'The Origin of Life',
    'International Conference on Evolution',
    '2011-09-15',
    4,
  ],
  [
    'The Theory of Everything',
    'International Conference on Theoretical Physics',
    '2011-10-10',
    5,
  ],
  [
    'The Evolution of Species',
    'International Conference on Evolution',
    '2011-11-05',
    6,
  ],
  [
    'The Structure of DNA',
    'International Conference on Molecular Biology',
    '2011-12-01',
    7,
  ],
  [
    'The Secret of Photosynthesis',
    'International Conference on Botany',
    '2012-01-15',
    8,
  ],
  [
    'The Nature of Light',
    'International Conference on Optics',
    '2012-02-10',
    9,
  ],
  [
    'The Function of the Brain',
    'International Conference on Neuroscience',
    '2012-03-05',
    10,
  ],
  [
    'The Human Genome Project',
    'International Conference on Genetics',
    '2012-04-01',
    11,
  ],
  [
    'The Causes of Climate Change',
    'International Conference on Environmental Science',
    '2012-05-15',
    12,
  ],
  [
    'The Dynamics of Galaxies',
    'International Conference on Astrophysics',
    '2012-06-10',
    13,
  ],
  [
    'The Future of Energy',
    'International Conference on Energy',
    '2012-07-05',
    14,
  ],
  [
    'The Origin of the Solar System',
    'International Conference on Astronomy',
    '2012-08-01',
    15,
  ],
  [
    'The Structure of Proteins',
    'International Conference on Biochemistry',
    '2012-09-15',
    16,
  ],
  [
    'The Diversity of Life',
    'International Conference on Biology',
    '2012-10-10',
    17,
  ],
  [
    'The Science of Aging',
    'International Conference on Gerontology',
    '2012-11-05',
    18,
  ],
  [
    'The Physics of Particles',
    'International Conference on Particle Physics',
    '2012-12-01',
    18,
  ],
  [
    'The Causes of Earthquakes',
    'International Conference on Geology',
    '2013-01-15',
    20,
  ],
  [
    'The Nature of Black Holes',
    'International Conference on Astrophysics',
    '2013-02-10',
    21,
  ],
  [
    'The Evolution of Language',
    'International Conference on Linguistics',
    '2013-03-05',
    22,
  ],
  [
    'The Structure of Materials',
    'International Conference on Materials Science',
    '2013-04-01',
    23,
  ],
  [
    'The Science of Sleep',
    'International Conference on Sleep Medicine',
    '2013-05-15',
    24,
  ],
  [
    'The Physics of Waves',
    'International Conference on Wave Physics',
    '2013-06-10',
    25,
  ],
  [
    'The Origin of the Universe',
    'International Conference on Cosmology',
    '2013-07-05',
    26,
  ],
  [
    'The Diversity of Cultures',
    'International Conference on Cultural Studies',
    '2013-08-01',
    27,
  ],
  [
    'The Science of Happiness',
    'International Conference on Positive Psychology',
    '2013-09-15',
    20,
  ],
  [
    'The Structure of the Earth',
    'International Conference on Geology',
    '2013-10-10',
    1,
  ],
  [
    'The Nature of Time',
    'International Conference on Time and Relativity',
    '2013-12-01',
    12,
  ],
];

export { authorsData, papersData, mentorsData };
